version: '3'

services:
    mysql:
        image: mysql:5
        environment:
            - MYSQL_ROOT_PASSWORD: root
            - MYSQL_DATABASE: privacytube
        volumes:
            - ./mysql_data:/var/lib/mysql

    privacytube:
        image: 0xhtml/privacytube:latest
        depends_on:
            - mysql
        environment:
            - mysql_host: mysql
            - mysql_pass: root
            - api_key
        ports:
            - 8080:80
